import { useSupabaseClient } from '@supabase/auth-helpers-react';
import Head from 'next/head';

import { useUser } from '@/hooks/useUser';

const Home: NextPageWithLayout = () => {
  const supabase = useSupabaseClient();
  const { user, isLoading } = useUser();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {user && (
          <button
            className="btn"
            onClick={async () => {
              await supabase.auth.signOut();
            }}
          >
            Sign out
          </button>
        )}
      </main>
    </div>
  );
};

Home.isPrivate = true;

export default Home;
